applications:
- name: daytrader-ee6
  memory: 2048M
  disk_quota: 1024M
  instances: 1
  host: dt
  domain: apps.pcf.gsic-sus.net
  env: 
    DAYTRADER3_CONTEXT_ROOT_URL: "https://dt.apps.pcf.gsic-sus.net"
    